# Generated by Django 4.1.4 on 2022-12-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no name', max_length=100)),
                ('genre', models.CharField(default='no location', max_length=100)),
                ('description', models.CharField(default='no division', max_length=100)),
                ('release_year', models.CharField(default='no wins', max_length=100)),
                ('director', models.CharField(default='no wins', max_length=100)),
                ('actor', models.CharField(default='no wins', max_length=100)),
                ('avg_score', models.CharField(default='no wins', max_length=100)),
                ('photo_url', models.CharField(default='no wins', max_length=100)),
                ('has_watched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='no name', max_length=100)),
                ('last_name', models.CharField(default='no location', max_length=100)),
                ('email', models.CharField(default='no division', max_length=100)),
                ('password', models.CharField(default='no wins', max_length=100)),
                ('watched', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='no name', max_length=100)),
                ('title', models.CharField(default='no location', max_length=100)),
                ('body', models.CharField(default='no division', max_length=100)),
                ('rating', models.CharField(default='no wins', max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film_project.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film_project.user')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='film_project.user'),
        ),
    ]
