# Generated by Django 4.1.4 on 2022-12-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watched',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='no username', max_length=100),
        ),
    ]
