# Generated by Django 4.1.4 on 2022-12-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0002_remove_user_watched_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='game',
            new_name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.CharField(default='no cover url', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(default='no actor', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_score',
            field=models.CharField(default='no average score', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='no description', max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='no director', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='no genre', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo_url',
            field=models.CharField(default='no photo url', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(default='no release year', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(default='no body', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default='no rating', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(default='no username', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='no email', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='no first name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='no last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='no password', max_length=100),
        ),
    ]
