# Generated by Django 4.1.4 on 2022-12-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0004_movie_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(default='no body', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film_project.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(default='no rating', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='no title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='film_project.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(default='no username', max_length=100, null=True),
        ),
    ]
