# Generated by Django 4.1.4 on 2023-01-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0005_alter_review_body_alter_review_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
