# Generated by Django 4.1.4 on 2023-01-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_url',
            field=models.CharField(default='no pic', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(default='no body', max_length=500, null=True),
        ),
    ]
