# Generated by Django 4.1.4 on 2023-01-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0007_review_profile_url_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='has_watched',
            field=models.CharField(default='no has watched', max_length=100),
        ),
    ]
