# Generated by Django 4.1.4 on 2023-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0008_alter_movie_has_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='no pic', max_length=700),
        ),
    ]
