# Generated by Django 4.1.4 on 2023-01-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_project', '0009_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='color',
            field=models.CharField(default='no color', max_length=100),
        ),
    ]
